services:
  _defaults:
    autowire: true
    public: false

  GingerPayments\Payments\Command\ReadLogsCommand:
    class: GingerPayments\Payments\Command\ReadLogsCommand
    arguments:
      $logFilePath: '%app.log_file_path%'
    tags:
      - { name: 'console.command', command: 'oetemplate:logger:read' }