parameters:
  app.log_file_path: '/var/www/source/log/modules_GingerPayments-oxid.log'

imports:
  - { resource: src/Command/services.yaml }

services:

  _defaults:
    public: false
    autowire: true
    bind:
      OxidEsales\Eshop\Core\Request: '@=service("OxidEsales\\ModuleTemplate\\Core\\Registry").getRequest()'

  GingerPayments\Payments\Core\Registry:
    class: OxidEsales\Eshop\Core\Registry
    public: true

  GingerPayments\Payments\Service\BasketItemLogger:
    class: GingerPayments\Payments\Service\BasketItemLogger
    public: true
    arguments:
      $logger: '@GingerPayments\Payments\Logger'

  GingerPayments\Payments\Logger:
    class: Monolog\Logger
    factory: [ '@GingerPayments\Payments\Logger\Factory', 'create' ]

  GingerPayments\Payments\Logger\Factory:
    class: OxidEsales\EshopCommunity\Internal\Framework\Logger\Factory\MonologLoggerFactory
    arguments:
      $configuration: '@GingerPayments\Payments\Logger\Configuration'

  GingerPayments\Payments\Logger\Configuration:
    class: OxidEsales\EshopCommunity\Internal\Framework\Logger\Configuration\MonologConfiguration
    arguments:
      $loggerName: 'Basket Logger'
      $logFilePath: '%app.log_file_path%'
      $logLevel: !php/const Psr\Log\LogLevel::DEBUG

  GingerPayments\Payments\Service\:
    resource: 'src/Service/*'
    public: true

  GingerPayments\Payments\Subscriber\BeforeModelUpdate:
    class: GingerPayments\Payments\Subscriber\BeforeModelUpdate
    tags: [ 'kernel.event_subscriber' ]